### ISSUE TITLE
Construct 2.8+ unsupported

### ISSUE THREAD

**Issue by JayFoxRox** [moyix/pdbparse#41]
This means one has to install a legacy module. This project should be upgraded to work with the newer Construct for easier installation.

**Comment by rohaaan** [comment]
FYI
use command pip install construct==2.5.2
the setup.py says construct <= 2.5.2

**Comment by rohaaan** [comment]
FYI
use command pip install pefile==2016.3.28
setup.py does not mention it but this version works flawless

**Comment by moyix** [comment]
Should be fixed as of https://github.com/moyix/pdbparse/pull/46
