### ISSUE TITLE
Porting pdbpase to construct 2.9

### ISSUE THREAD

**Issue by VPaulV** [moyix/pdbparse#45]
Hi guys, 

I am trying to port pdbparse to the last construct version, but got to one place that I don't understand. Here: https://github.com/moyix/pdbparse/blob/dbbd55def11e4bd8820e79bac6f43efb479661d8/pdbparse/tpi.py#L1070

What is this Tunnel? In old documentation and source code I found only TunnelAdapter. Didn't find any analogue with the same functionality int the new construct.

Thank you!

**Comment by moyix** [comment]
Tunnel applies a construct to a sequence of bytes returned by some other construct as a substream. I think the general ability to do tunneling is still in `construct`; there's a bit of information here:

https://construct.readthedocs.io/en/latest/tunneling.html

**Comment by moyix** [comment]
This should be fixed as of https://github.com/moyix/pdbparse/pull/46
